import Head from 'next/head';
import { useEffect } from 'react';
export const getServerSideProps = () => ({
  props: {
    test: 5,
  },
});

export default function Home({ test }) {
  useEffect(() => {
    console.log(test);
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      hello
    </div>
  );
}
